/*
 * FrameHorarioCiclo.java
 *   Encargado de un horario semanal para sesiones a grupo, asesorias u otras actividades
 * Parte de proyecto: SADAA
 * Author: Pedro Cardoso Rodriguez
 * Mail: ingpedro@live.com
 * Place: Zacatecas Mexico
 * 
    Copyright © 2010 Pedro Cardoso Rodriguez

    SADAA is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or any 
    later version.

    SADAA is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SADAA.  If not, see <http://www.gnu.org/licenses/>
 */

package sistema;

import definiciones.TipoMensaje;
import iconos.Iconos;


/** Ventana con un control encargado de un horario semanal para 
 *   sesiones a grupo, asesorias u otras actividades
 * 
 * @author  Pedro Cardoso Rdoriguez
 */
public class FrameHorarioCiclo extends sistema.ModeloFrameInterno{
    
    private ControlDiasSemana horarioSemanal;
    
    /** Crea un nuevo FrameHorarioCiclo
     * @param ventana Referencia a la ventana principal contenedora (clase sistema.FramePrincipal)
     */
    public FrameHorarioCiclo(sistema.FramePrincipal ventana){
        super(ventana,"frmhorasem.png");
        try {
            initComponents();
            btnActu.setText("");
            btnActu.setIcon(Iconos.getIcono("cargar.png"));
            horarioSemanal = new ControlDiasSemana("Distribucion de horario semanal vigente","",this);
            add(horarioSemanal, java.awt.BorderLayout.CENTER);
            cargaActividades();
        }
        catch (ControlDiasSemana.RefSuperiorInvalida ex){}
    }
    
    /**Carga los datos de horarios que aplican actualmente*/
    private void cargaActividades(){
        if(!horarioSemanal.cargaDatos()){
            muestraMensaje("Error al consultar horario semanal vigente",horarioSemanal.obtenError(),TipoMensaje.ERROR);
            return;
        }
        horarioSemanal.setTitulo("Horario semanal vigente");
        empaqueta();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnActu = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Horario semanal vigente");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnActu.setText("Actualiza");
        btnActu.setToolTipText("Actualizar tabla de actividades");
        btnActu.setFocusable(false);
        btnActu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActuActionPerformed(evt);
            }
        });
        jToolBar1.add(btnActu);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Vuelve a cargar los datos de horarios que aplican actualmente
     * @param evt El ActionEvent que genero el evento
     */
    private void btnActuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActuActionPerformed
        cargaActividades();
    }//GEN-LAST:event_btnActuActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActu;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    
}
