/*
 * FrameAyuda.java
 *  Ventana para mostrar el manual de usuario del sistema
 * Parte de proyecto: SADAA
 * Author: Pedro Cardoso Rodriguez
 * Mail: ingpedro@live.com
 * Place: Zacatecas Mexico
 * 
    Copyright © 2010 Pedro Cardoso Rodriguez

    SADAA is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or any 
    later version.

    SADAA is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SADAA.  If not, see <http://www.gnu.org/licenses/>
 */

package sistema;

import iconos.Iconos;
import javax.swing.JOptionPane;
import javax.swing.event.HyperlinkEvent;

/** Ventana para mostrar el manual de usuario del sistema
 * 
 * @author Pedro Cardoso Rodríguez
 */
public class FrameAyuda extends javax.swing.JFrame {
    
    /** Creaun nuevo FrameAyuda */
    public FrameAyuda() {
        String dirBase=System.getProperty("user.dir");
        initComponents();
        setIconImage(Iconos.getIcono("ayuda.png").getImage());
        setSize(750,625);
        setLocationRelativeTo(null);   
        cargaPagina("file:///"+cambiaDiag(dirBase)+"/manUser/index.html");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jepCaja = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manual de usuario");

        jepCaja.setEditable(false);
        jepCaja.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                jepCajaHyperlinkUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(jepCaja);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Envia a cargar una pagina web al hacer click en un enlace html del contenido del control jepCaja
     * @param evt El HyperlinkEvent que genero el evento
     */
    private void jepCajaHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_jepCajaHyperlinkUpdate
        if ( evt.getEventType()==HyperlinkEvent.EventType.ACTIVATED)
                  cargaPagina(evt.getURL().toString());
    }//GEN-LAST:event_jepCajaHyperlinkUpdate
    
    /** Cambia en una cadena la diagonal \ por /
     * @param src La cadena a procesar
     * @return La cadena procesada
     */
    private String cambiaDiag(String src){
        String cmb="";
        for(int g=0;g<src.length();g++){
            char c=src.charAt(g);            
            cmb+=""+(c=='\\'?c='/':c);
        }
        return cmb;
    }
    
    /** Carga una pagina web en el control jepCaja
     * @param pag La url de la pagina a cargar
     */
    private void cargaPagina(String pag){
        try {
            jepCaja.setPage(pag);
        }
        catch(java.io.IOException excIO) {
            JOptionPane.showMessageDialog(this,excIO.getMessage(),"Error al cargar el tema de ayuda",JOptionPane.ERROR_MESSAGE );
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane jepCaja;
    // End of variables declaration//GEN-END:variables
    
}
