/*
 * FrameAcerca.java
 *  Ventana para mostrar algunos datos acerca de del sistema
 * Parte de proyecto: SADAA
 * Author: Pedro Cardoso Rodriguez
 * Mail: ingpedro@live.com
 * Place: Zacatecas Mexico
 * 
    Copyright © 2010 Pedro Cardoso Rodriguez

    SADAA is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or any 
    later version.

    SADAA is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SADAA.  If not, see <http://www.gnu.org/licenses/>
 */

package sistema;

/** Es una ventana interna (JInternalFrame) para mostrar los datos [acerca de] de SADAA
 * 
 * @author  Pedro Cardoso Rodriguez
 */
public class FrameAcerca extends sistema.ModeloFrameInterno{
    
    /** Crea una nueva ventana FrameAcerca
     * @param ventana Referencia a la ventana principal contenedora (clase sistema.FramePrincipal)
     */
    public FrameAcerca(sistema.FramePrincipal ventana){
        super(ventana,"aplicacion.png");
        JPanImagen imgFondo=new JPanImagen();
        initComponents();
        lblVersion.setText("<html>Versión: <b>"+getVersion()+"</b></html>");
        pnlImag.add(imgFondo,java.awt.BorderLayout.CENTER);
        pnlImag.remove(lblDesc);
        imgFondo.setLayout(null);
        imgFondo.add(lblDesc);
        lblDesc.setLocation(70,15);
        lblDesc.setSize(400,200);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblVersion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        lblLiberacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblLicencia = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        pnlImag = new javax.swing.JPanel();
        lblDesc = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Acerca de");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema para la Administración de Datos de Actividades Académicas ");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblVersion.setText("Versión:");

        jLabel4.setText("Correo electrónico:");

        txtMail.setEditable(false);
        txtMail.setText(" ingpedro@live.com ");

        lblLiberacion.setText("<html>Ultima liberación:<br><b>Mayo 2010</b><br><br>Análisis y Desarrollo:<br><b>Pedro Cardoso Rodríguez</b></html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVersion)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLiberacion)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVersion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLiberacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        lblLicencia.setText("<html><center><br><b>Copyright © 2010 Pedro Cardoso Rodríguez</b><br><br>Software proporcionado bajo los términos de la licencia <b>GNU GENERAL PUBLIC LICENSE</b><br>Para más detalles consulte el archivo: LicenciaGPL.txt o visite el sitio: http://www.gnu.org/licenses<br><br>Las siguientes librerías son desarrollo de <em>Apache Software Foundation</em><br>bajo la licencia: (vea el archivo LICENSE.commons.txt)<br><b>The Apache Software License, Version 1.1</b><br>commons-beanutils-1.8.0.jar<br>commons-collections-2.1.jar<br>commons-digester-1.7.jar<br>commons-logging-1.0.2.jar<br><br>La siguiente librería esta bajo la licencia:<br><b>LGPL Version 2.1</b> (vea el archivo licenseLGPL.txt)<br>jasperreports-3.5.2.jar<br><br><b>Iconos</b> algunos son derivados de iconos del paquete: <em> famfamfam Silk icon set 1.3</em><br>Vea el archivo: LicenciaIconos.txt o visite: http://www.famfamfam.com/lab /icons/silk/<br>Iconos sin Copyright. Fuentes:<br>Creados por: Pedro Cardoso Rodríguez<br>Sitio http://www. lawebdelprogramador.com<br></center></html>");
        jScrollPane1.setViewportView(lblLicencia);

        btnAceptar.setMnemonic('e');
        btnAceptar.setText("Cerrar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        pnlImag.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlImag.setLayout(new java.awt.BorderLayout());

        lblDesc.setText("<html>SADAA tiene como prop&oacute;sito auxiliar al docente nivel licenciatura<br>en la administraci&oacute;n y elaboraci&oacute;n de reportes sobre datos de<br>alumnos y grupos a su cargo as&iacute; como el manejo de referencias<br>a material bibliogr&aacute;fico (Catalogo bibliogr&aacute;fico).</html>");
        pnlImag.add(lblDesc, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlImag, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlImag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Cierra la ventana acercade
     * @param evt El ActionEvent que genero el evento
     */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        cerrarVentana(getTitle());
    }//GEN-LAST:event_btnAceptarActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblLiberacion;
    private javax.swing.JLabel lblLicencia;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JPanel pnlImag;
    private javax.swing.JTextField txtMail;
    // End of variables declaration//GEN-END:variables
   
    /** Control que despliega como fondo una imagen*/
    private class JPanImagen extends javax.swing.JPanel{
        /** Crea un nuevo JPanImagen */
        public JPanImagen(){ super(); }
        
        /** Sobreescribe el paintComponent para que dibuje en el fondo del control una imagen
         * @param g El Graphics a utilizar
         */
        @Override
        public void paintComponent(java.awt.Graphics g){
            java.awt.Dimension dim = getSize();
            javax.swing.ImageIcon imagen=iconos.Iconos.getIcono("acerca.png");
            g.drawImage(imagen.getImage(),0,0,365,150,null);
            this.setOpaque(false);
            super.paintComponent(g);
        }
    }
    
}
