/*
 * FrameBusca.java
 *  Ventana para buscar registro de grupos en la base de datos
 * Parte de proyecto: SADAA
 * Author: Pedro Cardoso Rodriguez
 * Mail: ingpedro@live.com
 * Place: Zacatecas Mexico
 * 
    Copyright © 2010 Pedro Cardoso Rodriguez

    SADAA is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or any 
    later version.

    SADAA is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SADAA.  If not, see <http://www.gnu.org/licenses/>
 */

package grupos;

import database.Consultas;
import definiciones.TipoMensaje;
import iconos.Iconos;
import operaciones.Datos;

/** Es una ventana interna (JInternalFrame) desde la cual se puede buscar
 *  registro de grupos en la base de datos
 * 
 * @author Pedro Cardoso Rodríguez
 */
public class FrameBusca extends sistema.ModeloFrameInterno{
    
    /**Descripcion de la ultima busqueda*/
    private String desc;
    /**Las claves de la materias que imparte el docente registradas en la bd*/
    private String[] clvsMats;
    
    /** Crea una nueva ventana FrameBusca
     * @param ventana Referencia a la ventana principal contenedora (clase sistema.FramePrincipal)
     */
    public FrameBusca(sistema.FramePrincipal ventana){
        super(ventana,"frmbusca.png");
        initComponents();
        String[] materias;
        btnBuscar.setIcon(Iconos.getIcono("busca.png"));
        btnLimpia.setIcon(Iconos.getIcono("borra.png"));
        materias=Consultas.consultaLista("select clvm,nombre from materias order by nombre;",false);
        if(materias==null){
            muestraMensaje("Error al consultar lista de materias",Consultas.obtenError(),TipoMensaje.ERROR);
            clvsMats=null;
        }
        else if(materias[0]!=null){
            clvsMats=new String[materias.length];
            for(int g=0;g<materias.length;g++){
                clvsMats[g]=materias[g].substring(0,3);
                jcbMaterias.addItem(materias[g].substring(4));
            }
            jcbMaterias.setSelectedIndex(-1);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpOpcGnral = new javax.swing.ButtonGroup();
        btnGrpTpBus = new javax.swing.ButtonGroup();
        jLabel15 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtGrd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGrp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFcha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jcbMaterias = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        btnLimpia = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        rbtnTpBusO = new javax.swing.JRadioButton();
        rbtnTBusY = new javax.swing.JRadioButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconifiable(true);
        setTitle("Búsqueda de grupos");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Indique los criterios de búsqueda");

        btnBuscar.setMnemonic('B');
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Grado:");

        jLabel3.setText("Grupo:");

        jLabel5.setText(" Vigente en fecha:");

        jLabel8.setText("Materia:");

        btnLimpia.setMnemonic('L');
        btnLimpia.setText("Limpiar campos");
        btnLimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Buscar Grupo(s) que cumplan con:");

        btnGrpTpBus.add(rbtnTpBusO);
        rbtnTpBusO.setSelected(true);
        rbtnTpBusO.setText("Al menos un criterio");

        btnGrpTpBus.add(rbtnTBusY);
        rbtnTBusY.setText("Todos los criterios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtnTpBusO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnTBusY))
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbMaterias, 0, 382, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtGrd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtGrp, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtFcha, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtGrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtFcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jcbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpia)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnTpBusO)
                    .addComponent(rbtnTBusY)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Llama al metodo que valida y forma la sentencia sql de busqueda de grupos
     *  y en caso de obtener la sentencia realiza la consulta en la bd para mostrar los
     *  resultados obtenidos
     * @param evt
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String sentencia = validaParamsAndMkSentence();
        String clave;
        if(sentencia!=null){
            javax.swing.table.DefaultTableModel modTabla = Consultas.consTipoTable(sentencia,true);
            if(modTabla==null)
                muestraMensaje("Error al tratar de consultar el servidor", Consultas.obtenError(),TipoMensaje.ERROR);
            else if(modTabla.getRowCount()==0)
                muestraMensaje("Resultados de la busqueda", "No hubo resultados para esta busqueda",TipoMensaje.ERROR);
            else if(modTabla.getRowCount()==1){
                clave=""+modTabla.getValueAt(0,0);
                getPrincipalVnt().agregaVentanaGrupo(clave,1);
            } 
            else{
                String[] acols={"Clave","140","Grado","45","Grupo","45","Materia","200"};
                String[] mnus={"Ver ficha","Ver calendario","Ver rubros de evaluación"};
                cargaBusqueda(modTabla,"Grupos",desc,acols,mnus,false);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**  valida los parametros de busqueda y forma la sentencia sql de consulta
     * @return la sentencia sql de consulta o null en caso de encontrar al menos un dato invalido
     */
    private String validaParamsAndMkSentence(){
        String[] params;
        String iniComCons="select Grupos.ClvG as 'Clave', Grado, Grupo, nombre as 'Materia', PerIni as 'Inicio',";
        iniComCons+=" PerFin as 'Fin', Aula from Grupos, Imparte, Materias";
        String whereComCons=" where (";
        String concat=(rbtnTpBusO.isSelected()?" or ":" and ");
        boolean bandera;
        int aux;
        params = new String[4];
        params[0]=txtGrd.getText().trim();
        params[1]=txtGrp.getText().trim();
        params[2]=(jcbMaterias.getSelectedIndex()>=0?clvsMats[jcbMaterias.getSelectedIndex()]:"");
        params[3]=txtFcha.getText().trim();
        desc="";
        bandera=true;
        for(int h=0;h<params.length;h++) bandera=(bandera && params[h].equals(""));
        if(bandera){
            muestraMensaje("Error en los parámetros","Debe indicar al menos una parámetro",TipoMensaje.ERROR);
            return null;
        }
        try{
            aux=Integer.parseInt(params[0]);
            bandera=(aux<=0);
        }
        catch(NumberFormatException nbfExc){ bandera=true; }
        if(!params[0].equals("") && bandera){
            muestraMensaje("Error en el parámetro","Grado invalido",TipoMensaje.ERROR);
            return null;
        }
        else if((!params[3].equals("")&&!Datos.valFecha(params[3]))){
            muestraMensaje("Error en los parámetros","Formato de fecha incorrecto",TipoMensaje.ERROR);
            return null;
        }
        whereComCons+=(params[0].equals("")?"":"(grado="+params[0]+")");
        bandera=!params[0].equals("");
        desc+=(params[0].equals("")?"":"(Grado,"+params[0]+")");
        whereComCons+=(params[1].equals("")?"":(bandera?concat:"")+"(grupo='"+params[1]+"')");
        bandera=(bandera || !params[1].equals(""));
        desc+=(params[1].equals("")?"":(desc.equals("")?"":"+")+"(Grupo,"+params[1]+")");
        whereComCons+=(params[2].equals("")?"":(bandera?concat:"")+"Materias.ClvM='"+params[2]+"'");
        bandera=(bandera || !params[2].equals(""));
        desc+=(params[2].equals("")?"":(desc.equals("")?"":"+")+"(Materia,"+jcbMaterias.getSelectedItem()+")");
        if(!params[3].equals("")){
            whereComCons+=(bandera?concat:"")+" not(datediff(PerIni,'"+Datos.transformatFcha(params[3])+"')";
            whereComCons+=">0 or datediff(PerFin,'"+Datos.transformatFcha(params[3])+"')<0)";
            desc+=(desc.equals("")?"":"+")+"(Vigente,"+params[3]+")";
        }
        return iniComCons+whereComCons+") and (Materias.ClvM=Imparte.ClvM and Grupos.ClvG=Imparte.ClvG) order by grado;";
    }
 
    /** Limpia los controles y reinicializa los valores  necesarios para 
     * ofrecer la opciond e crear un nuevo registro de grupo
     * @param evt El ActionEvent que genero el evento
     */
    private void btnLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiaActionPerformed
        txtGrd.setText("");
        txtGrp.setText("");
        txtFcha.setText("");
        jcbMaterias.setSelectedIndex(-1);
    }//GEN-LAST:event_btnLimpiaActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.ButtonGroup btnGrpOpcGnral;
    private javax.swing.ButtonGroup btnGrpTpBus;
    private javax.swing.JButton btnLimpia;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox jcbMaterias;
    private javax.swing.JRadioButton rbtnTBusY;
    private javax.swing.JRadioButton rbtnTpBusO;
    private javax.swing.JTextField txtFcha;
    private javax.swing.JTextField txtGrd;
    private javax.swing.JTextField txtGrp;
    // End of variables declaration//GEN-END:variables
    
}
