/*
 * FrameBusca.java
 *  Ventana encargada de recibir y procesar los parametros de busqueda de alumnos
 * Parte de proyecto: SADAA
 * Author: Pedro Cardoso Rodríguez
 * Mail: ingpedro@live.com
 * Place: Zacatecas Mexico
 * 
    Copyright © 2010 Pedro Cardoso Rodriguez

    SADAA is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or any 
    later version.

    SADAA is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SADAA.  If not, see <http://www.gnu.org/licenses/>
 */

package alumnos;

import definiciones.TipoMensaje;
import iconos.Iconos;
import operaciones.Datos;

/**  Es una ventana interna (JInternalFrame) la cual sirve para la busqueda de 
 *  registros de alumnos.
 * 
 * @author Pedro Cardoso Rodríguez
 */
public class FrameBusca extends sistema.ModeloFrameInterno{
    
    /** Guarda una descripcion del tipo de busqueda mas reciente */
    private String desc;
    
    /** Crea una nueva ventana FrameBusca
     * @param ventana Referencia a la ventana principal contenedora 
     *   (sistema.FramePrincipal)
     */
    public FrameBusca(sistema.FramePrincipal ventana){
        super(ventana,"frmbusca.png");
        initComponents();
        btnBuscar.setIcon(Iconos.getIcono("busca.png"));
        btnLimpia.setIcon(Iconos.getIcono("borra.png"));
        validate();
        pack();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpNom = new javax.swing.ButtonGroup();
        btnGrpApp = new javax.swing.ButtonGroup();
        btnGrpFNac = new javax.swing.ButtonGroup();
        btnGrpFIng = new javax.swing.ButtonGroup();
        btnGrpDom = new javax.swing.ButtonGroup();
        btnGrpMun = new javax.swing.ButtonGroup();
        btnGrpMnuBus = new javax.swing.ButtonGroup();
        btnGrpApm = new javax.swing.ButtonGroup();
        btnGrpAndOr = new javax.swing.ButtonGroup();
        pnlBusDPer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFIng = new javax.swing.JTextField();
        txtFNac = new javax.swing.JTextField();
        rbtnFeNacAntes = new javax.swing.JRadioButton();
        rbtnFeNacExac = new javax.swing.JRadioButton();
        rbtnFeIngAntes = new javax.swing.JRadioButton();
        rbtnFeIngExac = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBuNom = new javax.swing.JTextField();
        rbtnNomEx = new javax.swing.JRadioButton();
        rbtnNomSim = new javax.swing.JRadioButton();
        txtBuApp = new javax.swing.JTextField();
        rbtnAppEx = new javax.swing.JRadioButton();
        rbtnAppSim = new javax.swing.JRadioButton();
        rbtnFeNacDesp = new javax.swing.JRadioButton();
        rbtnFeIngDesp = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        txtBuDom = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBuMun = new javax.swing.JTextField();
        rbtnMunEx = new javax.swing.JRadioButton();
        rbtnMunSim = new javax.swing.JRadioButton();
        rbtnDomEx = new javax.swing.JRadioButton();
        rbtnDomSim = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBuApm = new javax.swing.JTextField();
        rbtnApmEx = new javax.swing.JRadioButton();
        rbtnApmSim = new javax.swing.JRadioButton();
        pnlOpciones = new javax.swing.JPanel();
        btnLimpia = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        rbtnTpBusO = new javax.swing.JRadioButton();
        rbtnTBusY = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconifiable(true);
        setTitle("Búsqueda de alumnos");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Por fechas:");

        jLabel6.setText("De ingreso:");

        jLabel5.setText("De nacimiento:");

        btnGrpFNac.add(rbtnFeNacAntes);
        rbtnFeNacAntes.setText("Antes de");

        btnGrpFNac.add(rbtnFeNacExac);
        rbtnFeNacExac.setSelected(true);
        rbtnFeNacExac.setText("Exacta");

        btnGrpFIng.add(rbtnFeIngAntes);
        rbtnFeIngAntes.setText("Antes de");

        btnGrpFIng.add(rbtnFeIngExac);
        rbtnFeIngExac.setSelected(true);
        rbtnFeIngExac.setText("Exacta");

        jLabel2.setText("Nombre(s):");

        jLabel3.setText("Ap Paterno:");

        btnGrpNom.add(rbtnNomEx);
        rbtnNomEx.setText("Valor exacto");

        btnGrpNom.add(rbtnNomSim);
        rbtnNomSim.setSelected(true);
        rbtnNomSim.setText("Valor similar");

        btnGrpApp.add(rbtnAppEx);
        rbtnAppEx.setText("Valor exacto");

        btnGrpApp.add(rbtnAppSim);
        rbtnAppSim.setSelected(true);
        rbtnAppSim.setText("Valor similar");

        btnGrpFNac.add(rbtnFeNacDesp);
        rbtnFeNacDesp.setText("Despues de");

        btnGrpFIng.add(rbtnFeIngDesp);
        rbtnFeIngDesp.setText("Despues de");

        jLabel10.setText("Domicilio:");

        jLabel11.setText("Municipio: ");

        btnGrpMun.add(rbtnMunEx);
        rbtnMunEx.setText("Valor exacto");

        btnGrpMun.add(rbtnMunSim);
        rbtnMunSim.setSelected(true);
        rbtnMunSim.setText("Valor similar");

        btnGrpDom.add(rbtnDomEx);
        rbtnDomEx.setText("Valor exacto");

        btnGrpDom.add(rbtnDomSim);
        rbtnDomSim.setSelected(true);
        rbtnDomSim.setText("Valor similar");

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel7.setText("El formato de las fechas es: dd-mm-aaaa");

        jLabel8.setText("Ap Materno:");

        btnGrpApm.add(rbtnApmEx);
        rbtnApmEx.setText("Valor exacto");

        btnGrpApm.add(rbtnApmSim);
        rbtnApmSim.setSelected(true);
        rbtnApmSim.setText("Valor similar");

        org.jdesktop.layout.GroupLayout pnlBusDPerLayout = new org.jdesktop.layout.GroupLayout(pnlBusDPer);
        pnlBusDPer.setLayout(pnlBusDPerLayout);
        pnlBusDPerLayout.setHorizontalGroup(
            pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlBusDPerLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlBusDPerLayout.createSequentialGroup()
                        .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .add(jLabel3))
                            .add(jLabel8))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, pnlBusDPerLayout.createSequentialGroup()
                                .add(txtBuApm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(rbtnApmEx)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(rbtnApmSim))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, pnlBusDPerLayout.createSequentialGroup()
                                .add(txtBuNom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(rbtnNomEx)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(rbtnNomSim))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, pnlBusDPerLayout.createSequentialGroup()
                                .add(txtBuApp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(rbtnAppEx)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(rbtnAppSim))))
                    .add(pnlBusDPerLayout.createSequentialGroup()
                        .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel10)
                            .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(txtBuMun, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .add(txtBuDom, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                        .add(18, 18, 18)
                        .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pnlBusDPerLayout.createSequentialGroup()
                                .add(rbtnDomEx)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(rbtnDomSim))
                            .add(pnlBusDPerLayout.createSequentialGroup()
                                .add(rbtnMunEx)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(rbtnMunSim))))
                    .add(pnlBusDPerLayout.createSequentialGroup()
                        .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, pnlBusDPerLayout.createSequentialGroup()
                                .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(txtFIng, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .add(txtFNac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pnlBusDPerLayout.createSequentialGroup()
                                .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(rbtnFeNacAntes)
                                    .add(pnlBusDPerLayout.createSequentialGroup()
                                        .add(rbtnFeIngAntes)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(rbtnFeNacExac)
                                            .add(rbtnFeIngExac))))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(rbtnFeNacDesp)
                                    .add(rbtnFeIngDesp)))
                            .add(jLabel7))))
                .addContainerGap())
        );
        pnlBusDPerLayout.setVerticalGroup(
            pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlBusDPerLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(txtBuNom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(rbtnNomEx)
                    .add(rbtnNomSim))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(txtBuApp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(rbtnAppEx)
                    .add(rbtnAppSim))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(txtBuApm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(rbtnApmEx)
                    .add(rbtnApmSim))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(pnlBusDPerLayout.createSequentialGroup()
                        .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel10)
                            .add(txtBuDom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel11)
                            .add(txtBuMun, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(pnlBusDPerLayout.createSequentialGroup()
                        .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(rbtnDomEx)
                            .add(rbtnDomSim))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(rbtnMunEx)
                            .add(rbtnMunSim))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel4)
                    .add(jLabel7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlBusDPerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlBusDPerLayout.createSequentialGroup()
                        .add(rbtnFeNacDesp)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(rbtnFeIngDesp))
                    .add(pnlBusDPerLayout.createSequentialGroup()
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel6))
                    .add(pnlBusDPerLayout.createSequentialGroup()
                        .add(txtFNac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtFIng, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(pnlBusDPerLayout.createSequentialGroup()
                        .add(rbtnFeNacAntes)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(rbtnFeIngAntes))
                    .add(pnlBusDPerLayout.createSequentialGroup()
                        .add(rbtnFeNacExac)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(rbtnFeIngExac)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLimpia.setMnemonic('L');
        btnLimpia.setText("Limpiar campos");
        btnLimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Buscar alumno(s) que cumplan con:");

        btnGrpAndOr.add(rbtnTpBusO);
        rbtnTpBusO.setSelected(true);
        rbtnTpBusO.setText("Al menos un criterio");

        btnGrpAndOr.add(rbtnTBusY);
        rbtnTBusY.setText("Todos los criterios");

        org.jdesktop.layout.GroupLayout pnlOpcionesLayout = new org.jdesktop.layout.GroupLayout(pnlOpciones);
        pnlOpciones.setLayout(pnlOpcionesLayout);
        pnlOpcionesLayout.setHorizontalGroup(
            pnlOpcionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlOpcionesLayout.createSequentialGroup()
                .add(pnlOpcionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .add(pnlOpcionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(btnLimpia)
                        .add(pnlOpcionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pnlOpcionesLayout.createSequentialGroup()
                                .add(32, 32, 32)
                                .add(rbtnTpBusO)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(rbtnTBusY))
                            .add(pnlOpcionesLayout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 289, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(67, 67, 67)))
                .addContainerGap())
        );
        pnlOpcionesLayout.setVerticalGroup(
            pnlOpcionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlOpcionesLayout.createSequentialGroup()
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlOpcionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlOpcionesLayout.createSequentialGroup()
                        .add(jLabel14)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pnlOpcionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(rbtnTpBusO)
                            .add(rbtnTBusY)))
                    .add(btnLimpia))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Indique los criterios de búsqueda");

        btnBuscar.setMnemonic('B');
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlOpciones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel15, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(233, 233, 233)
                        .add(btnBuscar))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator1)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, pnlBusDPer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel15)
                    .add(btnBuscar))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlBusDPer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlOpciones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /** Llama el metodo que limpia el contenido de los controles (texto) para ingresar nuevos parametros de busqueda
     * @param evt El ActionEvent que genero el evento
     */
    private void btnLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiaActionPerformed
        limpiaCampos(pnlBusDPer);
    }//GEN-LAST:event_btnLimpiaActionPerformed

    /** Llama al metodo que valida los parametros de busqueda y forma la sentencia sql
     *   de busqueda, si los datos son validos hace la busqueda con la sentencia obtenida
     *   y muestra los registros encontrados, si encuentra uno solo muestra directamente el
     *   registro personal del alumno si encuentra dos o mas muestra una tabla 
     *   (ver sistema.FrameBusquedas) si no encuentra registro o hay error al consultar 
     *   muestra mensaje indicandolo.
     * @param evt El ActionEvent que genero el evento
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String sentencia = validaParamsAndMkSentence();
        String matricula;
        if(sentencia!=null){
            javax.swing.table.DefaultTableModel modTabla = database.Consultas.consTipoTable(sentencia,true);
            if(modTabla==null)
                muestraMensaje("Error al tratar de consultar el servidor", database.Consultas.obtenError(),TipoMensaje.ERROR);
            else if(modTabla.getRowCount()==0)
                muestraMensaje("Resultados de la búsqueda", "No hubo resultados para esta búsqueda",TipoMensaje.INFORMACION);
            else if(modTabla.getRowCount()==1){
                matricula=(String)modTabla.getValueAt(0,0);
                getPrincipalVnt().agregaVentanaAlumno(matricula,1);
            } 
            else{ 
                String[] acols={"Matricula","60","Apellido paterno","95","Apellido materno","95","Nombre","95"};
                String[] mnus={"Registro personal","Desempeño académico","Desempeño en grupo","Asesorías"};
                cargaBusqueda(modTabla,"Alumnos",desc,acols,mnus,true);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed
    
    /** Valida los parametros de busqueda ingresados y forma la sentencia de consulta (sql)
     * @return La sentencia sql de busqueda de acuerdo a los parametros ingresados o null si 
     *   hay parametros erroneos (cero parametros, fechas en formato invalido)
     */
    private String validaParamsAndMkSentence(){
        String[] params;
        String iniComCons="select matricula as 'Matricula',appat as 'Apellido paterno',apmat as 'Apellido materno',";
        iniComCons+="nom as 'Nombre',tcasa as 'Telefono',tmovil as 'Celular',correoe as 'Correo E.' from alumno";
        String whereComCons=" where ";
        String concat=(rbtnTpBusO.isSelected()?" or ":" and ");
        boolean bandera;
        params = new String[7];
        params[0]=txtBuNom.getText().trim();
        params[1]=txtBuApp.getText().trim();
        params[2]=txtBuApm.getText().trim();
        params[3]=txtBuDom.getText().trim();
        params[4]=txtBuMun.getText().trim();
        params[5]=txtFNac.getText().trim();
        params[6]=txtFIng.getText().trim();
        desc="";
        bandera=true;
        for(int h=0;h<params.length;h++){
            bandera=(bandera && params[h].equals(""));
        }
        if(bandera){
            muestraMensaje("Error en los parámetros","Debe indicar al menos una parámetro",TipoMensaje.ERROR);
            return null;
        }
        else if((!params[5].equals("")&&!Datos.valFecha(params[5]))
                || (!params[6].equals("")&&!Datos.valFecha(params[6]))){
            muestraMensaje("Error en los parámetros","Formato de fecha incorrecto",TipoMensaje.ERROR);
            return null;
        }
        whereComCons+=(params[0].equals("")?"":operaciones.Datos.formaCondicion("Nom",params[0],rbtnNomSim.isSelected()));
        bandera=!params[0].equals("");
        desc+=(params[0].equals("")?"":"(Nombre,"+params[0]+")");
        whereComCons+=(params[1].equals("")?"":(bandera?concat:"")+operaciones.Datos.formaCondicion("ApPat",params[1],rbtnAppSim.isSelected()));
        bandera=(bandera || !params[1].equals(""));
        desc+=(params[1].equals("")?"":(desc.equals("")?"":"+")+"(Paterno,"+params[1]+")");
        whereComCons+=(params[2].equals("")?"":(bandera?concat:"")+operaciones.Datos.formaCondicion("ApMat",params[2],rbtnApmSim.isSelected()));
        bandera=(bandera || !params[2].equals(""));
        desc+=(params[2].equals("")?"":(desc.equals("")?"":"+")+"(Materno,"+params[2]+")");
        whereComCons+=(params[3].equals("")?"":(bandera?concat:"")+operaciones.Datos.formaCondicion("Dom",params[3],rbtnDomSim.isSelected()));
        bandera=(bandera || !params[3].equals(""));
        desc+=(params[3].equals("")?"":(desc.equals("")?"":"+")+"(Domicilio,"+params[3]+")");
        whereComCons+=(params[4].equals("")?"":(bandera?concat:"")+operaciones.Datos.formaCondicion("Mun",params[4],rbtnMunSim.isSelected()));
        bandera=(bandera || !params[4].equals(""));
        desc+=(params[4].equals("")?"":(desc.equals("")?"":"+")+"(Municipio,"+params[4]+")");
        if(!params[5].equals("")){
            desc+=(desc.equals("")?"":"+")+"(Nacimiento,";
            if(rbtnFeNacAntes.isSelected()) {
                whereComCons+=(bandera?concat:"")+" datediff(FNac,'"+Datos.transformatFcha(params[5])+"')<0";
                desc+="antes:"+params[5]+")";
            }
            else if(rbtnFeNacExac.isSelected()) {
                whereComCons+=(bandera?concat:"")+" (FNac='"+Datos.transformatFcha(params[5])+"')";
                desc+="en:"+params[5]+")";
            }
            else{
                whereComCons+=(bandera?concat:"")+" datediff(FNac,'"+Datos.transformatFcha(params[5])+"')>0";
                desc+="despues:"+params[5]+")";
            }
        }
        bandera=(bandera || !params[5].equals(""));
        if(!params[6].equals("")){
            desc+=(desc.equals("")?"":"+")+"(Ingreso,";
            if(rbtnFeIngAntes.isSelected()){
                whereComCons+=(bandera?concat:"")+" datediff(FIng,'"+Datos.transformatFcha(params[6])+"')<0";
                desc+="antes:"+params[6]+")";
            }
            else if(rbtnFeIngExac.isSelected()){
                whereComCons+=(bandera?concat:"")+" (FIng='"+Datos.transformatFcha(params[6])+"')";
                desc+="en:"+params[6]+")";
            }
            else {
                whereComCons+=(bandera?concat:"")+" datediff(FIng,'"+Datos.transformatFcha(params[6])+"')>0";
                desc+="despues:"+params[6]+")";
            }
        }
        return iniComCons+whereComCons;
    }
    
    /** Recorre los componentes dentro de un control contenedor y limpia el contenido de los controles
     * de texto JTextField dejandolos vacios
     * @param compo El control contenedor a limpiar los textos
     */
    private void limpiaCampos(java.awt.Container compo){
        java.awt.Component[] ctrls = compo.getComponents(); 
        for(int j=0;j<ctrls.length;j++){ 
            if(ctrls[j] instanceof javax.swing.JPanel || ctrls[j] instanceof javax.swing.JScrollPane
                    || ctrls[j] instanceof javax.swing.JRootPane || ctrls[j] instanceof javax.swing.JLayeredPane
                    || ctrls[j] instanceof javax.swing.JViewport)
                limpiaCampos((java.awt.Container)ctrls[j]);
            else if(ctrls[j] instanceof javax.swing.JTextField) 
                ((javax.swing.JTextField)ctrls[j]).setText("");
        }
        validate();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.ButtonGroup btnGrpAndOr;
    private javax.swing.ButtonGroup btnGrpApm;
    private javax.swing.ButtonGroup btnGrpApp;
    private javax.swing.ButtonGroup btnGrpDom;
    private javax.swing.ButtonGroup btnGrpFIng;
    private javax.swing.ButtonGroup btnGrpFNac;
    private javax.swing.ButtonGroup btnGrpMnuBus;
    private javax.swing.ButtonGroup btnGrpMun;
    private javax.swing.ButtonGroup btnGrpNom;
    private javax.swing.JButton btnLimpia;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnlBusDPer;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JRadioButton rbtnApmEx;
    private javax.swing.JRadioButton rbtnApmSim;
    private javax.swing.JRadioButton rbtnAppEx;
    private javax.swing.JRadioButton rbtnAppSim;
    private javax.swing.JRadioButton rbtnDomEx;
    private javax.swing.JRadioButton rbtnDomSim;
    private javax.swing.JRadioButton rbtnFeIngAntes;
    private javax.swing.JRadioButton rbtnFeIngDesp;
    private javax.swing.JRadioButton rbtnFeIngExac;
    private javax.swing.JRadioButton rbtnFeNacAntes;
    private javax.swing.JRadioButton rbtnFeNacDesp;
    private javax.swing.JRadioButton rbtnFeNacExac;
    private javax.swing.JRadioButton rbtnMunEx;
    private javax.swing.JRadioButton rbtnMunSim;
    private javax.swing.JRadioButton rbtnNomEx;
    private javax.swing.JRadioButton rbtnNomSim;
    private javax.swing.JRadioButton rbtnTBusY;
    private javax.swing.JRadioButton rbtnTpBusO;
    private javax.swing.JTextField txtBuApm;
    private javax.swing.JTextField txtBuApp;
    private javax.swing.JTextField txtBuDom;
    private javax.swing.JTextField txtBuMun;
    private javax.swing.JTextField txtBuNom;
    private javax.swing.JTextField txtFIng;
    private javax.swing.JTextField txtFNac;
    // End of variables declaration//GEN-END:variables
    
}
